# docker-compose -f docker-compose.yml up -d
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    networks:
      docker-elk:

  crawler:
    image: docker.flohannes/news-crawler:core
    container_name: news-crawler
    command: localhost 720
    networks:
      - docker-elk
    depends_on:
      - elasticsearch

networks:
  docker-elk:
    driver: bridge